# Claude Code profile
# Use with: sx claude
network_mode = "online"

[filesystem]
allow_read = [
    "~/.claude",
    "~/.claude.json",
    "~/.claude.lock",
    "~/.local/share/claude",
    "~/.local/bin/claude",
    "~/.CFUserTextEncoding",
    "/private/tmp/claude*", # claude-UID directories (e.g. claude-501)
    "/private/tmp/zsh*", # When claude use zsh in bash it create dynamic tmp file
]
allow_write = [
    "~/.claude",
    "~/.claude.json",
    "~/.claude.lock",
    "~/.local/share/claude",
    "~/Library/Caches/claude-cli-nodejs/",
    "~/Library/Keychains/login.keychain-db", # OAuth token refresh
    "/private/tmp/claude*", # claude-UID directories (e.g. claude-501)
    "/private/tmp/zsh*", # When claude use zsh in bash it create dynamic tmp file
]

[shell]
pass_env = ["ANTHROPIC_API_KEY"]
