# Python toolchain profile
# Use with: sx python

[filesystem]
allow_read = [
    "~/.pyenv",
    "~/.local/share/virtualenvs",
    "~/.python_history",
    "/Library/Frameworks/Python.framework",
]
allow_write = [
    "~/.cache/pip",
]

[network]
allow_domains = [
    "pypi.org",
    "files.pythonhosted.org",
]
